# -*- coding: utf-8 -*-
"""CGS_TESTS1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_uD85EgiRb75qasiMl5Swlx8JWn499Gq
"""

#

import pandas as pd
import matplotlib.pyplot as plt
#https://www.w3schools.com/python/python_functions.asp
def doLinegraph2(xaxis, yaxis, title, xaxis_label, yaxis_label):
  #print(xaxis + " TEST")
  #xaxis2=[ i for i, j in locals().items() if j == xaxis][0]
  #yaxis2=yaxis
  import matplotlib.pyplot as plt
  plt.plot(xaxis, yaxis)
  plt.title(title)
  plt.xlabel(xaxis_label)
  plt.ylabel(yaxis_label)
  plt.show()



import pandas as pd
import matplotlib.pyplot as plt
#https://www.w3schools.com/python/python_functions.asp
def doLinegraph3(xaxis, yaxis, title, xaxis_label, yaxis_label):
  #print(xaxis + " TEST")
  #xaxis2=[ i for i, j in locals().items() if j == xaxis][0]
  #yaxis2=yaxis
  import matplotlib.pyplot as plt
  plt.plot(xaxis, yaxis)
  plt.title(title)
  plt.xlabel(xaxis_label)
  plt.ylabel(yaxis_label)
  plt.show()


import pandas as pd
import matplotlib.pyplot as plt
#https://www.w3schools.com/python/python_functions.asp
def doLinegraph4(xaxis, yaxis, title, xaxis_label, yaxis_label):
  #print(xaxis + " TEST")
  #xaxis2=[ i for i, j in locals().items() if j == xaxis][0]
  #yaxis2=yaxis
  import matplotlib.pyplot as plt
  plt.plot(xaxis, yaxis)
  plt.title(title)
  plt.xlabel(xaxis_label)
  plt.ylabel(yaxis_label)
  plt.show()
  #TEST1